
import numpy as np
import pandas as pd

SEASON_MAP = {
    12: "Winter", 1: "Winter", 2: "Winter",
    3: "Spring", 4: "Spring",
    5: "Summer", 6: "Summer",
    7: "Monsoon", 8: "Monsoon", 9: "Monsoon",
    10: "Autumn", 11: "Autumn",
}

BASE_FEATURES = [
    "PM2.5", "PM10", "NO2", "SO2", "CO", "O3", "NH3", "NOx",
    "Temperature", "Humidity", "WindSpeed", "Pressure", "Rainfall",
]

LEAK_COLS = ["AQI_Bucket"] 


def engineer(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["Month"] = df["Date"].dt.month
    df["Season"] = df["Month"].map(SEASON_MAP)

    df["PM_ratio"] = df["PM2.5"] / df["PM10"].replace(0, np.nan)
    df["PM_ratio"] = df["PM_ratio"].fillna(df["PM_ratio"].median())

    df["Pollutant_Load"] = (
        0.4 * df["PM2.5"] + 0.25 * df["PM10"] + 0.15 * df["NO2"]
        + 0.1 * df["SO2"] + 0.1 * df["CO"] * 10
    )

    df = df.drop(columns=[c for c in LEAK_COLS if c in df.columns])
    return df


def build_model_matrix(df: pd.DataFrame):
    """One-hot encode categoricals and return (X, y, feature_names).

    Only includes columns that actually exist in the dataframe — the real
    CPCB/Kaggle `city_day.csv` has no weather columns at all (Temperature,
    Humidity, WindSpeed, Pressure, Rainfall), while the synthetic demo data
    generated by make_demo_data.py does. This keeps the pipeline working on
    either source without code changes.
    """
    candidate_cols = BASE_FEATURES + ["PM_ratio", "Pollutant_Load", "Month"]
    feature_cols = [c for c in candidate_cols if c in df.columns]
    missing = [c for c in candidate_cols if c not in df.columns]
    if missing:
        print(f"[feature_engineering] columns not present in this dataset, "
              f"skipping: {missing}")

    cat_cols = [c for c in ["City", "Season"] if c in df.columns]

    X_num = df[feature_cols].copy()
    X_cat = pd.get_dummies(df[cat_cols], prefix=cat_cols, drop_first=True)
    X = pd.concat([X_num, X_cat], axis=1)
    y = df["AQI"].copy()
    return X, y, list(X.columns)


if __name__ == "__main__":
    from data_loader import load_raw
    from preprocessing import clean

    df = clean(load_raw())
    df = engineer(df)
    X, y, cols = build_model_matrix(df)
    print("Feature matrix shape:", X.shape)
    print("Features:", cols)
    df.to_csv("data/processed/city_day_features.csv", index=False)